### ISSUE TITLE
AAPS version support

### ISSUE THREAD

**Issue by 0xBABA** [swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface#11]
Hello 
I noticed the readme mentions AAPS as data source for dev builds later than 12/05/2023. 

I am running AAPS 3.2.0.2 which was released 12/11/2023. I assume (perhaps wrongfully) changes from dev branch committed on may would be merged into this version by Novemeber of the same year, but of course, this is an assumption.

In any case, I have the Garmin plugin enabled in AAPS with default port (28891). When I test it by going to http://127.0.0.1:28891/sgv.json?count=12&brief_mode=true as instructed, I am not getting anything. 

Am I wrong to expect this to work on my version?

**Comment by swissalpine** [comment]
Please update to 3.2.0.4

**Comment by 0xBABA** [comment]
Thank you. Upgrade to 3.2.0.4 seems to resolve this.
