### ISSUE TITLE
Xdrip Datafield not showing anything after activity resume later

### ISSUE THREAD

**Issue by blaqone** [swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface#2]
The data field does not show anything when an activity is resumed later. 

See picture
![image](https://user-images.githubusercontent.com/37814299/188308332-200961d0-9de3-4d09-8d9d-f94c2221338d.jpg)

This is on a forerunner 955

**Comment by swissalpine** [comment]
This seems to be a bug in the firmware of the fr955:
https://forums.garmin.com/beta-program/forerunner-955-series/public-beta-bug-reports/i/bug-reports---beta-12-20/ciq-data-fields-crash-if-you-resume-later-on-an-activity
