### ISSUE TITLE
Glucose data not showing after some time - all relevant apps are not restricted by data or battery savings

### ISSUE THREAD

**Issue by 0xBABA** [swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface#5]
Hello
I am using xDrip+ as data source. 
I turned off battery restrictions and enabled background data for xDrip, Garmin Connect, Bluetooth (system app) and Bluetooth services (system app). 
My phone is a pixel (5a) running android 13 (with Feb security update) and the watch is a Venu sq (SW ver 4.6).
With all of the above CGM data synchronization keeps dropping several times a day (I see data is live in xDrip when this happens - so the drop occurs somewhere between xDrip to Connect to from Connect to the watch).
Your input on this is welcome. 

Thanks!

**Comment by 0xBABA** [comment]
Hi and thanks.
How do you identify that the background process in the watch stops? Just by seeing there's no sync for aome time? If that is the case, i can't say that flipping up for a widget helps. 
What do you mean by wifi disabled? Where should i disbale wifi (and why?) 
There's no error message it just missing data from X minutes ago and bg is striked out. 

Thanks.

**Comment by nyancow** [comment]
@0xBABA did you end up solving this somehow? I am experiencing the same issue with a Venu Sq on a Samsung Galaxy device. Everything was actually working fine up until a couple months ago. Since then I am able to get some readings, but eventually they stop coming in and the BG is crossed out, for hours/days. I've almost given up on it but recently tried debugging it again. Tried both XDrip and AAPS as sources, played around with the delay time, even tried the constant 5min option, but no combination helps. The local ports for XDrip and AAPS are both working and reporting up to date values.

**Comment by 0xBABA** [comment]
For me changing to nightscout as data source improved the situation (still issues but much better than before) . I think it only pulls every 10 minutes with this configuration, but i'd rather get a reading every 10 minutes than spuriously not getting them at all.
I never tried AAPS as a source, didn't have it installed back then. Might give it a try...

**Comment by nyancow** [comment]
AAPS as a source is actually rather new, make sure you're on the latest version of AAPS. XDrip used to work great for me, I doubt it's an issue with the source. Do you see the Garmin Connect service notification constantly? Or does it come and go?

**Comment by nyancow** [comment]
@swissalpine any way I can debug this to pinpoint the issue? Feel free to get as technical as needed.

**Comment by swissalpine** [comment]
Have you disabled the optimations of the Bluetooth App (System Apps)?

**Comment by nyancow** [comment]
I looked into that, saw it mentioned in the readme, but I don't think there's an option to control the system Bluetooth app's battery usage on the latest Samsung Galaxy devices. There are no apps with "Bluetooth" in the name in the apps list, and I couldn't find a "System apps" list either.

**Comment by swissalpine** [comment]
Shure, it is (on my Samsung Flip 4 with Android 14):
![Screenshot_20240131_090230_Settings](https://github.com/swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface/assets/12517693/f4ddc847-8934-4056-be4c-f37abf732ae5)
![Screenshot_20240131_090245_Settings](https://github.com/swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface/assets/12517693/d55c2ba0-1287-4429-912d-a762569d9add)

**Comment by nyancow** [comment]
I can't believe I missed that, it's exactly where it always was. 🤦‍♂️  Thank you @swissalpine! I'll try disabling battery optimization for it and see if it has an effect on watch readings.
