### ISSUE TITLE
IoB, Carb data without AndroidAPS

### ISSUE THREAD

**Issue by bart2** [swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface#6]
Hello,

First of all, thank you for implementing this watch face. It has been super helpful in managing my T1 diabetes!

I recently discovered that xDrip+ allows adding meal carb and bolus values and will report estimated IoB values in the app: 
![Screenshot_20230618_113321_xDrip+](https://github.com/swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface/assets/14372325/decdd0a2-19e8-4f8a-8671-896ccd908889)

After some research I found that xDrip watch face already supports reporting IoB values, but only when full loop AndroidAPS is used.

Would it be possible to have an option to display xDrip+ IoB and carb values as data fields in the watch face?

Thanks!

**Comment by swissalpine** [comment]
Unfortunately, this is not possible because the endpoint that the watchface queries does not pass on this information. Only the aaps status is passed through. From this I isolate IOB, TBR and COB.

**Comment by bart2** [comment]
Thanks for the reply. I'll see if I could extend the xDrip+ endpoint to include that information.

To make testing possible, can I get added to the private repo containing the watch face source code (I noticed similar requests in other discussion threads :))

Thanks!

**Comment by bart2** [comment]
@swissalpine, I've added IoB reporting in xDrip+ with https://github.com/NightscoutFoundation/xDrip/pull/2928.

I started working on the Garmin side of things, when I realized the repo I got access to only contains the datafield source code. Can you also add me to the watch face source code repository? Thanks!

**Comment by swissalpine** [comment]
Done.
Please note that for the data field the code can hardly be larger, the limit is 26 kb for older devices.
