### ISSUE TITLE
Does this watch face's widget allow customisation of other watchfaces

### ISSUE THREAD

**Issue by renegadeandy** [swissalpine/GARMIN-xDrip-Spike-Nightscout-Watchface#7]
Hi,

I see that this watch face offers a widget. I am wondering if this widget will allow me to customise a watch faces and add my blood glucose level to the display on watch faces like:

https://apps.garmin.com/en-US/devices/venu-asia/appTypes/watchface/apps

Many thanks in advance!

**Comment by swissalpine** [comment]
No, unfortunately that's not possible / realised.

**Comment by renegadeandy** [comment]
Do you think there is any API / capability to add this? I would be happy to help coding it if the API's exist to let this happen.

**Comment by swissalpine** [comment]
Unfortunately, I don't know of possibilities to realise this but that doesn't necessarily mean there isn't one.
You know this: https://developer.garmin.com/connect-iq/api-docs/?
